---
title: "Pre-Work"
---

::: callout-tip
## Post-Workshop Update
Git and GitHub were not used in this workshop. The Website modules were updated to use Netlify Drop instead of Git and GitHub.
:::

## Day 1

-   Download or update the latest versions of R, RStudio, Quarto:

    -   R `4.3` (or 4.2 or above): <https://cran.r-project.org>

    -   RStudio `2023.06.0+421` or above: <https://posit.co/download/rstudio-desktop>

    -   Quarto `1.3.433` or above: <https://quarto.org/docs/get-started>

-   Install the following R packages by opening RStudio and typing the following in the Console [^1]

```{r}
#| eval: false
#| echo: true
pkg_list <- c(
  "tinytex", "quarto", "knitr", "here", "yaml"
)
install.packages(pkg_list)
```

[^1]: See this [video tutorial](https://www.youtube.com/watch?v=u1r5XTqrCTQ) for step-by-step instructions

-   Register an account with Quarto Pub[^2]: <https://quartopub.com>

-   Download and unzip [`day01-exercises.zip`](day01-exercises.zip). Then, go to RStudio \> File \> New Project \> Existing Directory and navigate to the unzipped `day01-exercises` folder and create an RStudio project[^3] in there and open it.

[^3]: For more about RStudio Projects see this [explainer](https://support.posit.co/hc/en-us/articles/200526207-Using-RStudio-Projects)

## Day 2

-   Keep adding content to `replication-pkg/`
-   Check out Quarto websites and see if there are any features you'd particularly like to learn:
    - See [Awesome Quarto](https://github.com/mcanouil/awesome-quarto#websites-formats) or my website [cynthiahqy.com](https://www.cynthiahqy.com)

