project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about.qmd"
    - "00-pre-workshop.qmd"
    - "01*/*.qmd"
    - "02*/*.qmd"
    - "03*/*.qmd"
    - "!exercises-upload/"
  resources:
    - "day01-exercises.zip"

website:
  page-navigation: true
  title: "Meeting AEA Replication standards using Quarto and GitHub"
  description: "Jul 18-20 Workshop on Quarto for Department of Economics, Monash University"

  repo-url: https://github.com/cynthiahqy/monash-quarto-aea
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@cynthiahqy"

  sidebar:
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2

    tools:
      - icon: github
        href: https://github.com/cynthiahqy/monash-quarto-aea
        text: "GitHub organization"

    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: 00-pre-workshop.qmd
        text: Pre-work
      - text: "---"
      - section: "Getting to Know Quarto"
        contents:
          - href: 01a-hello-quarto/index.qmd
            text: Hello Quarto!
          - href: 01b-formats/index.qmd
            text: Document Formats
          - href: 01c-articles/index.qmd
            text: Articles
          - href: 01d-wrap-up/index.qmd
      - text: "---"
      - section: "AEA Replication in Quarto"
        contents:
          - href: 02a-template/index.qmd
            text: Replication Package Template
          - text: Websites
            href: 02c-websites-pt1/index.qmd
          - href: 02d-wrap-up/index.qmd
      - text: "---"
      - section: "Producing and Publishing Websites"
        contents:
          - text: Websites Cont'd
            href: 03a-websites-pt2/index.qmd
          - text: Publish
            href: 03b-publish/index.qmd
          - text: Tools and Customisation
            href: 03c-misc/index.qmd
          - href: 03d-wrap-up/index.qmd
      - text: "---"
      - section: "More Quarto for Academics"
        contents:
          - text: Includes
          - text: (TBC) Listings
          - text: (TBC) Presentations
          - text: Wrap Up

  page-footer:
    right: "This page is built with 💚 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Cynthia Huang"

format:
  html:
    theme: cosmos
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

editor: visual
