### Getting to Know Quarto

<!--- using quarto to produce different formats from the same file --->

+---------------+----------------+-----------------------------------------+
| Time          | Module         | **Section & Activities**                |
+===============+================+=========================================+
| 09:00-09:15   | Hello Quarto!  | Welcome                                 |
+---------------+----------------+-----------------------------------------+
| 09:15-09:35   |                | What is Quarto?                         |
|               |                |                                         |
|               |                | -   My Turn: A Tour of Rstudio          |
+---------------+----------------+-----------------------------------------+
| 09:35-09:50   |                | Your Turn: `my_first_doc.qmd`           |
|               |                |                                         |
|               |                | -   Source/Visual mode + basic Markdown |
+---------------+----------------+-----------------------------------------+
| 09:50-10:00   |                | Your Turn: Rendering in Rstudio         |
|               |                |                                         |
|               |                | -   alternative methods, under the hood |
+---------------+----------------+-----------------------------------------+
| 10:00-10:10   | PAUSE          |                                         |
+---------------+----------------+-----------------------------------------+
| 10:10-10:25   | Quarto Formats | Anatomy of a Document                   |
|               |                |                                         |
|               |                | Quarto Formats                          |
|               |                |                                         |
|               |                | -   Our Turn: Rendering Other Formats   |
+---------------+----------------+-----------------------------------------+
| 10:25-10:40   |                | YAML                                    |
|               |                |                                         |
|               |                | -   Your Turn: Quarto YAML Intelligence |
+---------------+----------------+-----------------------------------------+
| 10:40-10:50   | PAUSE          |                                         |
+---------------+----------------+-----------------------------------------+
| 10:50-11:20   | Articles       |                                         |
+---------------+----------------+-----------------------------------------+
| 10:20-11:30   | WRAP-UP        |                                         |
+---------------+----------------+-----------------------------------------+

Notes:

- Ran overtime to 12PM
- Lots of troubleshooting with PDF rendering:
    - introduce `latex` format earlier
    - put render `.qmd` to `.pdf` in prework!

Next time:

- Rtools needed to install tinytex on Windows computers
- include aside on MathJax in Articles / LaTex
- FOCUS on PDF/Tex output first!
    - introduce multi-format rendering earlier!
- My Turn: A Tour should be more impressive!
    - go straight for elsivier template!
- Sign up questions:
    - markdown?
    - git/GitHub?
- Swap Articles and Doc Formats order
    - show valid YAML = render dropdowns in RStudio


### AEA Replication Package using Quarto (2.5 Hours)

<!--- using quarto to collect bits into documents ----->

| Time | Module                                |
|------|---------------------------------------|
|      | Reproducibility in Social Sciences    |
|      |                                       |
|      | Replication Package Template          |
|      |                                       |
|      | Websites                              |
|      |                                       |
|      | Wrap-Up                               |

Notes:

- Put Our Turn: get template at the end 2a
    - Next time: distribute template as starter zip

- skipped Includes because of issues with rendering
- wrapped up at 2.30PM

### Publishing Quarto Websites online (2.5 Hours)

<!---- taking documents and turning them into a website --->

| Time | Module            |
|------|-------------------|
|      | Includes          |
|      | Listings          |
|      | Publishing Online |
|      |                   |
|      | Wrap-Up           |

- Next time:
    - starter site with more docs for listings

```zsh
quarto create-project listings-web
cd listings-web
mkdir events
for i in {1..3}; do touch events/event-0$i.qmd; done
for i in {1..3}; do echo "---\ntitle:\"Event ${i}\"\n---" >> events/event-0$i.qmd; done
mkdir posts
for i in {1..9}; do touch posts/article-0$i.qmd; done
for i in {1..9}; do echo "---\ntitle:\"Article ${i}\"\n---" >> posts/article-0$i.qmd; done
touch people.yml
```

### More Quarto for Academics (2.5 Hours)

| Time | Module                                 |
|------|----------------------------------------|
|      | Personal Websites and Blogs            |
|      |                                        |
|      | Presentations and Teaching with Quarto |
|      |                                        |
|      | Miscellaneous                          |
|      | Wrap-Up                                |