## Workshop Abstract

::: callout-tip
## Post-Workshop Update
Git and GitHub were not used in this workshop. The abstract below has been updated to reflect this change.
:::

This workshop aims to enable participants to adapt existing projects and workflows to meet AEA Replication standards. Participants will learn how to use features from Quarto markdown to organise code scripts and data analysis according to the Data and Code Availability Standard \[Version 1.0\] [@koren2022], and how to publish a companion website.

In this workshop, participants will:

-   improve their understanding of AEA replication standards

-   learn to include coding scripts (STATA, MATLAB, R, Python etc.), tables, figures, citations and mathematical equations in Quarto documents

-   produce a replication package and website using a provided Quarto template

-   learn how to publish a replication website online using Netlify Drop

-   *(optional)* learn about additional Quarto features such as presentation slides and custom document styling

Quarto is an open-source framework for authoring scientific and technical documents in formats such as HTML, PDF, MS Word, and more.

## Instructor: Cynthia Huang, PhD student

Cynthia is a second year PhD student in Econometrics and Business Statistics at Monash University working on principles and methods for data preparation. She completed honours in Economics at the University of Melboure and has extensive experience preparing data for empirical economics research. She uses Quarto and GitHub to document R and python code, write papers and presentation slides, and to publish her personal website. Her CV can be viewed on her website (built with Quarto): <https://www.cynthiahqy.com/cv>