---
title: "Wrap-Up"
subtitle: "Session 2: AEA Replication in Quarto"
date: 2023-07-18
format: revealjs
metadata-files: 
  - ../_slides.yml
---

## Reproducibility in Social Sciences

::: incremental

- Replication involves both computational requirements and documentation
- Quarto can help with documentation even if you don't use R/Python
- Consider preparing your replication package inside a Quarto website project using [🔗 github.com/cynthiahqy/quarto-replication-template](https://github.com/cynthiahqy/quarto-replication-template)
:::

## Quarto Websites

::: incremental
- Websites are type of Quarto project
- Projects all contain a `_quarto.yml` config file
- You can build a website around existing code, data and papers!
:::

## Day 2 Pre-Work

-   If you're not familar with using git from inside RStudio or the command line, please install the latest version of GitHub Desktop: <https://desktop.github.com>

Optional:

-   Keep adding content to `replication-pkg/`
-   Check out Quarto websites and see if there are any features you'd particularly like to learn:
    - See [Awesome Quarto](https://github.com/mcanouil/awesome-quarto#websites-formats) or my website [cynthiahqy.com](https://www.cynthiahqy.com)

## Questions

::: task
Any questions / anything you'd like to review or learn before we wrap up the workshop?
:::

::: task
Suggestions / requests for things to cover in Thursday's session?
:::