# Quarto Journal Articles

## Available Features

Quarto Journal Article Extentions supports

-   a standardized schema for authors and affiliations that can be expressed once int the source document,

-   the use of Citation Style Language (CSL) to automate the formatting of citations and bibliographies, and

-   outputting to `pdf`, `html`, and `docx` with custom formatting,

. . .

according to the styles required for various journals,

. . .

and creating the LaTeX required for submission to multiple journals.

## Journal formats {.smaller}

::: learn-more
[github.com/quarto-journals](https://github.com/quarto-journals)
:::

| Journal / Publisher                       | Name                                                                          |
|-------------------------------------------|-------------------------------------------------------------------------------|
| Association of Computing Machinery        | [acm](https://github.com/quarto-journals/acm)                                 |
| American Chemical Society                 | [acs](https://github.com/quarto-journals/acs)                                 |
| American Geophysical Union                | [agu](https://github.com/quarto-journals/agu)                                 |
| Biophysical journal                       | [biophysical-journal](https://github.com/quarto-journals/biophysical-journal) |
| Elsevier Journals                         | [elsevier](https://github.com/quarto-journals/elsevier)                       |
| American Statistical Association Journals | [jasa](https://github.com/quarto-journals/jasa)                               |
| Journal of Statistical Software           | [jss](https://github.com/quarto-journals/jss)                                 |
| Public Library of Science                 | [plos](https://github.com/quarto-journals/plos)                               |

## Getting started with a journal article

The `quarto use template` command can be used to create an article from one these formats, e.g. for JASA:

```{.bash filename="Terminal"}
quarto use template quarto-journals/jasa
```

## Our Turn: Journal Article Templates

